In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

Pytorch is an open source python deep learning library. It's one the most widely used deep learning library for research since 2019. It is popular because of it's user friendly interface and efficiency. It is accessible, flexible and allows adavanced users to tweak lower level aspects of their models for customization and optimization.

Core components of PyTorch - 

1. Tensor Library - PyTorch library implements a tensor array for efficient computing
2. Automatic Differentiation Engine - PyTorch includes utilities to differentiate computations automatically.
3. Deep learning library. - Deep learning utilities that use of above two

So Tensors are the fundamental building blocks for computing, the automatic differentiation engine for model optimization, and deep learning utility functions to implement and train deep neural network models.

Let's now look at Tensors in detail.

Tensors are similar to NumPy's ndarrays, except that tensors can run on GPU's and other hardware accelerators. It extends the concepts of array-oriented programming library NumPy with the additional feature of accelerated computation offering seamless switch between CPU and GPU. Tensors and NumPy arrays can often share the same underlying memory, eliminating copy data. Tensors are also optimized for Automatic Differentiation which we will explore later. Tensors are mainly used to encode inputs and outputs of a model, as well as the model'parameters. 

Let's go ahead to explore about Tensor's - 

In [2]:
import torch
import numpy as np

In [3]:
# Intializing a Tensor - Using data directly

data = [[1,2],[3,4]]
x_data = torch.tensor(data)

In [4]:
x_data

tensor([[1, 2],
        [3, 4]])

In [5]:
# Intializing a Tensor - Using NumPy Array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [6]:
# Intializing a Tensor - Using another tensor

x_ones = torch.ones_like(x_data) # Retains the properties of x_data like the size being 2 x 2

print(f'Ones Tensor: \n {x_ones} \n')

x_rand = torch.rand_like(x_data, dtype = torch.float)
print(f'Random Tensor: \n {x_rand} \n')


Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.0850, 0.0577],
        [0.5549, 0.3657]]) 



In [7]:
shape = (3,7,) # Tuple of tensor dimensions
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f'Random Transfer: \n {rand_tensor} \n')
print(f'Only ones Transfer: \n {ones_tensor} \n')
print(f'Only Zeros Transfer: \n {zeros_tensor} \n')

Random Transfer: 
 tensor([[0.9985, 0.5419, 0.5461, 0.5122, 0.0614, 0.9933, 0.4674],
        [0.8258, 0.7042, 0.3407, 0.8222, 0.8005, 0.6865, 0.9770],
        [0.7691, 0.6607, 0.2300, 0.3265, 0.2822, 0.7063, 0.4871]]) 

Only ones Transfer: 
 tensor([[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]]) 

Only Zeros Transfer: 
 tensor([[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]]) 



Attributes of a Tensor

Tensor attributes describe their shape, datatype, and the device one which they are stored.

In [8]:
tensor = torch.rand(2,5)
print(f'Tensor shape: {tensor.shape} \n')
print(f'Tensor datatype: {tensor.dtype} \n')
print(f'Device Tensor is stored on: {tensor.device} \n')

Tensor shape: torch.Size([2, 5]) 

Tensor datatype: torch.float32 

Device Tensor is stored on: cpu 



**Operations on Tensors**

There are over 1200 operations including arithmetic, linear algebra, matrix multiplication (transposing, indexing, slicing), sampling and more.

By default tensors created on CPU. We need to explicitely move the tensors to the accelerator using .to method (after checking for it's availabilty). Copying tensors across devided can be expensive in terms of time and memory. Why? Let's find out.

In [9]:
# Move tensor to the current accelerator if available
if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())
    print(tensor.device)

cuda:0


In [10]:
# Standard numpy like indexing and slicing
tensor = torch.tensor([[1,2],[3,4],[5,6]])
print(f'First Row: {tensor[0]} \n')
print(f'First Column: {tensor[:, 0]} \n')
print(f'Last Column: {tensor[...,-1]} \n')
tensor[:,1] = 0
print(tensor)

First Row: tensor([1, 2]) 

First Column: tensor([1, 3, 5]) 

Last Column: tensor([2, 4, 6]) 

tensor([[1, 0],
        [3, 0],
        [5, 0]])


In [11]:
# Joining tensors to concatenate a sequence of tensors along a given dimension.
t1 = torch.cat([tensor,tensor],dim=1)
print(t1)

t2 = torch.stack((tensor,tensor))
print(t2)

tensor([[1, 0, 1, 0],
        [3, 0, 3, 0],
        [5, 0, 5, 0]])
tensor([[[1, 0],
         [3, 0],
         [5, 0]],

        [[1, 0],
         [3, 0],
         [5, 0]]])


In [12]:
y1 = tensor.T # Transpose operation
print(y1)

y2 = tensor.matmul(tensor.T)
print(y2)

z1 = tensor * tensor
z2 = tensor.mul(tensor)

print(f'z1: {z1}\n')
print(f'z2: {z2}\n')

tensor([[1, 3, 5],
        [0, 0, 0]])
tensor([[ 1,  3,  5],
        [ 3,  9, 15],
        [ 5, 15, 25]])
z1: tensor([[ 1,  0],
        [ 9,  0],
        [25,  0]])

z2: tensor([[ 1,  0],
        [ 9,  0],
        [25,  0]])



In [13]:
agg = tensor.sum()
print(agg)
agg_item = agg.item()
print(agg_item, type(agg_item))

tensor(9)
9 <class 'int'>


In [14]:
# In-place operations
tensor.add_(5)
print(tensor)

# In-place operations can save some memory, but can be problematic becuse of an immediate loss of history.
# Hence, their use is discouraged.

tensor([[ 6,  5],
        [ 8,  5],
        [10,  5]])
